
import type { Metadata } from "next";

import "./globals.css";
import { Navbar } from "@/components/shared/Navabr";

import { Providers } from "@/services/productApi/providers";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

 
  return (
    <html lang="en">
      <body
        className='space-y-4'
      >
        <Navbar></Navbar>
      
        <Providers> {children}</Providers>
       
       
      </body>
    </html>
  );
}
